on:
  schedule:
  - cron: "0 4 * * 3"
  workflow_dispatch:

jobs:
  update:
    name: Update crew data from datacore repo
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - run: |
        cd static
        rm crew.json
        ./scripts/transform_crew

    - uses: stefanzweifel/git-auto-commit-action@v5
